name: Build mbusd

on:
  push:
    branches:
      - master
      - cicd
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 9 * * 0"
  workflow_dispatch:

jobs:
  build-mbusd:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        arch:
          - armv7l
          - arm
    env:   
      xcompile_vars: 'CC=${{matrix.arch}}-linux-musleabihf-gcc CXX=${{matrix.arch}}-linux-musleabihf-g++ INCLUDE="-I/usr/${{matrix.arch}}-linux-musleabihf/include/"'

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up cross-compiler
      uses: dawidd6/action-download-artifact@v2
      with:
        repo: coolitsystemsinc/cdu-build
        github_token: ${{ secrets.ACTIONS_AUTH }}        
        workflow: musl-artifact.yaml
        workflow_conclusion: success
        name: ${{ matrix.arch }}-linux-musleabihf-cross
        path: .

    - name: Copy cross-compiler to usr folder
      run: |
        tar -xvf ${{ matrix.arch }}-linux-musleabihf-cross.tgz
        sudo cp -r ./${{ matrix.arch }}-linux-musleabihf-cross/* /usr/

    - name: Compile mbusd
      run: |
        chmod +x *
        autoreconf -if
        ./configure --prefix=/usr/${{ matrix.arch }}-linux-musleabihf/ --host=${{ matrix.arch }}-linux-musleabihf
        sudo make install ${{ env.xcompile_vars }}
        ls -alR /usr/${{ matrix.arch }}-linux-musleabihf/
    
    - name: Upload mbusd binary
      uses: actions/upload-artifact@v2
      with:
        name: mbusd-${{ matrix.arch }}
        path: /usr/${{ matrix.arch }}-linux-musleabihf/bin/mbusd
