name: Build mbusd

on:
  push:
    branches:
      - master
      - ci*
  pull_request:
    branches:
      - master
  
jobs:
  build-mbusd:
    name: Run cross-compiler download and verification for each architecture
    strategy:
      matrix:
        arch:
          - arm-linux-musleabihf
          #- aarch64-linux-musl
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Download musl-cross-compiler library from release
      id: musl-cross-compiler
      uses: robinraju/release-downloader@v1.8
      with:
        repository: coolitsystemsinc/cdu-lib
        latest: true
        token: ${{ secrets.ACTIONS_AUTH }}
        fileName: "${{ matrix.arch }}-cross.tgz"
        extract: false
        out-file-path: .

    - name: Copy cross-compiler to usr folder
      run: |
        tar -xvf ${{ matrix.arch }}-cross.tgz
        sudo cp -r ./${{ matrix.arch }}-cross/* /usr/
        
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/cmake/${{ matrix.arch }}.cmake

    - name: Build the cmake
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config Release

    - name: Make
      run: |
        cd ${{github.workspace}}/build
        make
      
    - name: Upload mbusd binary
      uses: actions/upload-artifact@v4
      with:
        name: mbusd-${{ matrix.arch }}
        path: ${{github.workspace}}/build/mbusd
