name: Build mbusd

on:
  push:
    branches:
      - main
      - cicd
  pull_request:
    branches:
      - main

env:
  xcompile_vars: 'CC=arm-linux-gnueabihf-gcc CXX=arm-linux-gnueabihf-g++ INCLUDE="-I/usr/arm-linux-gnueabihf/include/"'

jobs:
  build-mbusd:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up cross-compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf

    - name: Compile mbusd
      run: |
        chmod +x *
        autoreconf -if
        ./configure --prefix=/usr/arm-linux-gnueabihf/
        sudo make
        sudo make install
        ls -al /usr/arm-linux-gnueabihf/bin/
    
    - name: Upload mbusd binary
      uses: actions/upload-artifact@v2
      with:
        name: mbusd
        path: /usr/arm-linux-gnueabihf/bin/mbusd
