name: Build mbusd

on:
  push:
    branches:
      - master
      - cicd
  pull_request:
    branches:
      - master
  schedule:
      - cron: "0 9 * * 0"
  
env:
  xcompile_vars: 'CC=arm-linux-musleabihf-gcc CXX=arm-linux-musleabihf-g++ INCLUDE="-I/usr/arm-linux-musleabihf/include/"'

jobs:
  build-mbusd:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up cross-compiler
      uses: dawidd6/action-download-artifact@v2
      with:
        repo: coolitsystemsinc/cdu-build
        github_token: ${{ secrets.ACTIONS_AUTH }}        
        workflow: musl-artifact.yaml
        workflow_conclusion: success
        name: arm-linux-musleabihf-cross
        path: .

    - name: Copy cross-compiler to usr folder
      run: |
        tar -xvf arm-linux-musleabihf-cross.tgz
        sudo cp -r ./arm-linux-musleabihf-cross/* /usr/

    - name: Compile mbusd
      run: |
        chmod +x *
        autoreconf -if
        ./configure --prefix=/usr/arm-linux-musleabihf/ --host=arm-linux-musleabihf
        sudo make install ${{ env.xcompile_vars }}
        ls -alR /usr/arm-linux-musleabihf/
    
    - name: Upload mbusd binary
      uses: actions/upload-artifact@v2
      with:
        name: mbusd
        path: /usr/arm-linux-musleabihf/bin/mbusd
